[build]
  command = "bash netlify-build.sh"
  publish = "build/web"

[build.environment]
  NODE_VERSION = "20"
  # (اختياري) ثبّت نسخة Flutter:
  FLUTTER_VERSION = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
